use std::io::Error;

pub fn all() -> Result<(), Error> {
    return Ok(());
}
